<?php include('partials/header.php'); ?>
<?php include('partials/wvu-header.php'); ?>
<?php include('partials/hsc-header.php'); ?>
<?php include('partials/site-header.php'); ?>

<div id="hero">
    <div id="hero-color"></div>
    <div id="hero-content" class="measure">
        <h1>ZEN FRAMEWORK</h1>
        <p>A opinionated web framework designed to create a consistent structure with a flexible and efficient styling strategy. Greatly inspired by the CSS Zen Garden.</p>
    </div>
</div>

<div id="front" class="measure">
    
    <!-- This Core Will Be Generated By CMS -->
    <div class="grp grp-three">
        
        <div class="col col-one">
            
            <?php include('blocks/block-news.php'); ?>

        </div>    

        <div class="col col-two">
            
            <h1>What is the Zen Framework?</h1>
            <p>The Zen Framework is an opinionated set of HTML structures and elements that are designed to remain consistent across a large set of sites. This allows for rapid development within a shared templating environment.</p>
            <p>The core goal is that if a developer creates a design for the Zen Framework, then anyone in the world who is using the Zen Framework can adopt their design by simply using their CSS file. It's endlessly sharable.</p>
            <p>While the Zen Framework may not be the best fit for every project, it does provide great value to organizations and developers that manage an incredibly large number of sites within a central organization. Not only will it help developers design consistently, but it will also save a lot of time when creating and updating designs.</p>
            
            <h2>Getting Started</h2>
            <p>Since the framework itself is just a set of HTML structures, all you need to do is create a CSS file that targets all of the DOM elements in the framework.<p>
            <p>By taking advantage of OOCSS principles, organizing your CSS code is very easy. If you need a little help getting started, check out our starter kit CSS, Shelter.</p>

        </div>

        <div class="col col-three">
            
            <?php include('blocks/block-events.php'); ?>

        </div>

    </div>

</div>

<?php include('partials/site-footer.php'); ?>
<?php include('partials/wvu-footer.php'); ?>
<?php include('partials/footer.php'); ?>