<?php include('partials/top.php'); ?>
<?php include('partials/wvu-header.php'); ?>
<?php include('partials/hsc-header.php'); ?>
<?php include('partials/site-header.php'); ?>

<div id="hero">
    <div id="hero-color"></div>
    <div id="hero-content" class="measure">
        <h1>ZEN FRAMEWORK</h1>
        <p>An opinionated web framework designed to create a consistent structure with a flexible and efficient styling strategy. Greatly inspired by the CSS Zen Garden.</p>
    </div>
</div>

<div id="front" class="measure">
    
    <!-- This Core Will Be Generated By CMS -->

    
    <div class="grp grp-two">
    
        <div class="col col-one">
            <h1>Column One</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ex unde atque cupiditate dolorem quam quis doloremque porro magni assumenda animi vero, tempore magnam placeat iusto nihil ipsa at. Maxime!</p>
        </div>
        <div class="col col-two">
            <h1>Column Two</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quo temporibus adipisci veritatis omnis perferendis at nemo vero assumenda deserunt maiores ipsa, error eos cumque? Quo ex quos in molestiae.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil laborum blanditiis possimus placeat et earum, perspiciatis sequi voluptatum voluptatem, vel repellat. Nostrum magnam sapiente magni laudantium quidem beatae similique ex!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate tempora accusamus minus voluptatem aut, qui asperiores commodi placeat tempore veniam amet dolor, maiores, perferendis voluptates voluptatibus consectetur? Repudiandae minima, natus.</p>
        </div>

    </div>


    <div class="grp grp-four">
        
        <div class="col col-one">
            <h1>Column One</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ex unde atque cupiditate dolorem quam quis doloremque porro magni assumenda animi vero, tempore magnam placeat iusto nihil ipsa at. Maxime!</p>
        </div>
        <div class="col col-two">
            <h1>Column Two</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quo temporibus adipisci veritatis omnis perferendis at nemo vero assumenda deserunt maiores ipsa, error eos cumque? Quo ex quos in molestiae.</p>
        </div>
        <div class="col col-three">
            <h1>Column Three</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere aliquid soluta modi repellat ea accusamus, doloribus, veniam temporibus iure natus quia vel sed enim nihil, quaerat labore iste architecto autem.</p>
        </div>
        <div class="col col-four">
            <h1>Column Four</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit rerum quisquam dignissimos, deleniti! Ut laborum soluta ad itaque, fugiat ducimus tenetur nemo cupiditate iste quibusdam neque veniam molestiae, quos architecto.</p>
        </div>

    </div>


    <div class="grp grp-three">
        
        <div class="col col-one">
            
            <?php include('blocks/block-news.php'); ?>

        </div>    

        <div class="col col-two">
            
            <h1>What is the Zen Framework?</h1>
            <p>The Zen Framework is an opinionated set of HTML structures and elements that are designed to remain consistent across a large set of sites. This allows for rapid development within a shared templating environment.</p>
            <p>The core goal is that if a developer creates a design for the Zen Framework, then anyone in the world who is using the Zen Framework can adopt their design by simply using their CSS file. It's endlessly sharable.</p>
            <p>While the Zen Framework may not be the best fit for every project, it does provide great value to organizations and developers that manage an incredibly large number of sites within a central organization. Not only will it help developers design consistently, but it will also save a lot of time when creating and updating designs.</p>
            
            <h2>Getting Started</h2>
            <p>Since the framework itself is just a set of HTML structures, all you need to do is create a CSS file that targets all of the DOM elements in the framework.<p>
            <p>By taking advantage of OOCSS principles, organizing your CSS code is very easy. If you need a little help getting started, check out our starter kit CSS.</p>

        </div>

        <div class="col col-three">
            
            <?php include('blocks/block-events.php'); ?>

        </div>

    </div>

</div>

<?php include('partials/site-footer.php'); ?>
<?php include('partials/wvu-footer.php'); ?>
<?php include('partials/bottom.php'); ?>